channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=23.2.1
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - credit-card-defaulters==0.0.1
  - numpy==1.24.4
  - pandas==2.0.3
  - pyyaml==6.0.1
  - scikit-learn==1.0.2
  - scipy==1.11.1
name: mlflow-env
